### ISSUE TITLE
$ calculations on UI are not being generated correctly. For both pool deposits and user deposits - part 2

### ISSUE THREAD

**Issue by xatilla** [vesperfi/issues#24] opened 2021-11-28 23:40 UTC
**Re-opening as prior one was closed (https://github.com/vesperfi/issues/issues/23) but also to redirect notifications to this git user account**

The $ calculations on vesper.finance UI and orbit.vesper.finance are not being generated correctly for both pool deposits and user deposits.. The issue may be the source that is used to calculate the values of USDT/USD or FRAX/USD for conversion prices as they seem to be missing a digit of resolution.  See discord thread https://discord.com/channels/763794227116507156/763794227116507159/914305909356908594

example:
Pool total supply = 5,064,629 vUSDT
Pool token value = 1.019478 USDT/vUSDT
Pool deposits = Pool total supply x Pool token value = 5,163,278 USDT
USDT price =1.0008 USDT based on price oracle https://data.chain.link/ethereum/mainnet/stablecoins/usdt-usd
i.e 1000 USDT =1000.80 USD
Value locked  = Pool deposits x USDT price should be  5,167,408 USD (it currently displays values between 5,127,268 and 5146287 which implies their is a resolution issue)

Gab mentioned that current source has a value of 0.995127 USD/USDT but the price oracle 1.0008 so the true USD value is 5163278*1.0008 which is 5,167408,150.. Please compare current sources with price oracle.

Important: User deposits also seeing the same discrepancy ($FRAX) so other conversion prices may have same resolution issue

**Comment by gabmontes** [comment] 2021-11-29 15:29
@xatilla the USD/USDT rate you get come from Chainlink but we are using Uniswap/SushiSwap to get token exchange rates. So sometimes there are slight differences like in this case (~0.5%). Having that in mind, the math is correct and the displayed values, consistent. That's why I closed #23 in the first place.

Now, we all agree that using Chainlink to get the rates is probably a superior approach. Therefore and IMHO this is more like a "feature", an improvement or evolution of Vesper more than a fundamentally broken part that needs to be "fixed". And we are considering it.

**Comment by xatilla** [comment] 2021-11-29 15:53
Gab - you missed the bigger issue. you are dividing not multiplying. Do you agree that 100 USDT = 100.7 USD today ?, so why would your 5,163,279.2371 USDT value show a lower USD value.. it should  be higher. You need to multiply is.. even using uniswap, if i try and sell 5,163,279.2371 USDT, you will get $5,165,860, ...Go try it..  the UI is showing the # if you  had divide it, not multiply. I see the same on user deposit calculation (e.g FRAX)

**Comment by gabmontes** [comment] 2021-11-29 16:54
@xatilla we are using the same formula across all the pools. If there were a problem with it, all the other pools would be affected. And this is not the case. Therefore the math is correct.

Imagine if we were dividing instead of multiplying for pools like vWBTC where the factor is not ~1 but ~55k. The problem would be huge!

Now, the current rate we are getting from our sources are 0.994304 USD/USDT and 1.005964 USD/FRAX. Those are slightly different from what you get from Chainlink. And that explains the difference in what you expect from what is shown.

Makes sense now?

**Comment by xatilla** [comment] 2021-11-29 17:11
/yes, the calcs are wrong. Let me prove it.. 
you say 1USD = 0.994304 USD/USDT  ok
do you agree then then that 1005.72 USD =  1000 USDT based on that rate, agreed.
which implies that 5,165,860 USD = 5,163,279.2371  USDT...  agreed but your UI is showing 5137,569 
you are multiply when you need to dividing that USD/USDT rate

**Comment by gabmontes** [comment] 2021-11-29 17:45
> you say 1USD = 0.994304 USD/USDT ok

@xatilla not exactly. If the rate is 0.994304 USD/USDT that means 1 USDT equals 0.994304 USD.

> do you agree then then that 1005.72 USD = 1000 USDT based on that rate, agreed.

Considering the rate above, 1,000 USDT is 994.304 USD, not 1,005.72 USD.

> which implies that 5,165,860 USD = 5,163,279.2371 USDT... agreed but your UI is showing 5137,569

And therefore 5,163,279.2371 USDT are 5,133,869 USD, not 5,165,860 USD.

Think about this the following way: if 1 USDT is less than 1 USD, all USD values have to be less than the USDT values.

**Comment by xatilla** [comment] 2021-11-29 18:41
If I see 1000 USDT on uniswap I get $1001.32 right now, 
![uniswap_usdt](https://user-images.githubusercontent.com/92111179/143924083-44939a5e-599f-4b80-8261-726985e0f027.png)
If I sell 1000 USDT on FTX, I would get $1000.80 USD right now. If I sell 1000 USDT on binance, I would get $1000.70. See pics. attached. Go to https://app.uniswap.org/#/swap and tell me what $ value you see when you try to swap 1000 USDT ..you don't get 994, you get 1000+ USD

I bet a 1000 USD the UI is multiplying when it should be dividing..

and would prefer a blue chip defi platform sharing accurate USD conversion. 
![binance_usdt](https://user-images.githubusercontent.com/92111179/143923581-56253e35-ce8f-4e25-8a88-4ae0f49919bb.png)
![ftx_usdt](https://user-images.githubusercontent.com/92111179/143923593-136435f0-eae1-4ecf-b73f-56be64df7784.png)

**Comment by gabmontes** [comment] 2021-11-30 02:35
> I bet a 1000 USD the UI is multiplying when it should be dividing..

@xatilla as mentioned and explained earlier, this is not the case. The math is correct as it is the same for all the pools. There is no "special case" for USDT. All work or neither do. And the rest are ok so this is it.

The difference you point out is fully explained by the USDT-to-USD rate. And as mentioned earlier too, how we get those rates is something we continuously think about how to improve.

For this particular case of USDT where we are consistently getting a < 1 ratio we will perform a deeper analysis. If we find something wrong for sure we will fix it.

Thanks for bringing this into our attention!

**Comment by xatilla** [comment] 2021-11-30 04:23
Gab - one last attempt. I am convinced I'm right but this answer will satisfy me

Would you agree for USDT pool or for FRAX pool or for ETH pool, you should get USDT/USD rate or FRAX/USD rate or ETH/USD from uniswap/sushiswap and multiply it by qty , agreed ?
You have mentioned the USD/USDT rate which is the opposite of USDT/USD rate..
you said you have 0.994304 = USD/USDT rate which means the USDT/USD rate is 1.00572. that is what I am pointing out... you need inverted value in your stablecoin calcs..

**Comment by gabmontes** [comment] 2021-11-30 14:44
@xatilla stablecoins are not a special case and we [must] use the same calcs everywhere. This is not the problem at all.

After digging a bit more into this, it is clear that the root cause of this whole discussion is at [Uniswap's router contract](https://etherscan.io/address/0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D#code) rate responses. It says USDT/USDC rate is 0.993965 and USDC/USDT rate is 0.994052. You can check that by yourself.

We will for sure work on improving how the rates are obtained to be as accurate as possible.

**Comment by xatilla** [comment] 2021-11-30 15:14
ok, understood. Those rates from that contract are clearly wrong, terrible inaccurate source... It is having an impact as I see users deposit FRAX and question why the USD value is lower than what they deposited. I now understand its because we are using this uniswap source but also you are using USDC.. the USDC/USD rate is not 1.0 either so that is skeewing it more badly..  This really needs to be a priority to fix. Why can't we use the API https://data.chain.link/ethereum/mainnet/stablecoins/frax-usd and https://data.chain.link/ethereum/mainnet/stablecoins/usdt-usd for example..

**Comment by gabmontes** [comment] 2021-11-30 15:47
@xatilla We can and is one of the options we could take to improve on this area.

**Comment by gabmontes** [comment] 2021-12-13 19:03
Closing this issue as the calculations are correct. The improvements to get more accurate rates will be addressed as a different task.

**Closed as completed by gabmontes** 2021-12-13 19:03 UTC
